name: Lighthouse workflow
on: pull_request

jobs:
  build_app:
    name: Build app
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Bundle JS
      run: npm run build

    - name: Build image
      run: docker build -f ./internals/build/Dockerfile -t react-forecast-img .

    - name: Run container
      run: docker run -d -p 9000:80 react-forecast-img

    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v2
      with:
          urls: |
            http://localhost:9000
          runs: 3
          budgetPath: './performance-budget.json'

    - name: Save performance results
      uses: actions/upload-artifact@v1
      with:
        name: lighthouse-results
        path: '.lighthouseci'